name: gFB-1.0.2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openjdk=11.0.1
  - fastqc=0.11.8
  - multiqc=1.6
  - r-markdown=0.8
  - freebayes=1.2.0
  - bedtools=2.27.1
  - ea-utils=1.1.2.779
  - bwa=0.7.17
  - picard=2.18.17
  - samtools=1.9
  - qualimap=2.2.2b
