From:continuumio/miniconda:4.5.11
Bootstrap:docker

%labels
    MAINTAINER Sheng-Da Hsu
    DESCRIPTION Singularity image containing all requirements for the gFB pipeline
    VERSION 1.0.0

%environment
    PATH=/opt/conda/envs/gFB-1.0.0/bin:$PATH
    export PATH

%files
    environment.yml /
    resources /tmp

%post
    apt-get update --fix-missing
    apt-get install -y procps
    apt-get upgrade -y
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean -a
