---
title: "Sequence QC result"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
library(DT)
library(dplyr)
```

***

> __File path: files/1_Assembly/__

### Clean Read QC Summary

We are showing the clean read and merged reads QC summary here.  
If you are interested in raw reads quality, please feel free to contact us.

<a href="files/0_ReadQC/multiqc_report.html" target="_blank">QC Summary</a>

```{r, out.width = "700px", out.height="700px", echo=FALSE, message=FALSE, warning=FALSE}
knitr::include_url("files/0_ReadQC/multiqc_report.html")
```

***

### Reference
```
- "Trimmomatic v0.36": Read quality filtering & adapter trimming
Bolger, A. M., Lohse, M., & Usadel, B. (2014). Trimmomatic: A flexible trimmer for Illumina Sequence Data. Bioinformatics, btu170.

- "PEAR v0.9.6": Paired-end Read Merger
Zhang J, Kobert K, Flouri T, Stamatakis A. PEAR: a fast and accurate Illumina Paired-End reAd mergeR. Bioinformatics. 2014;30(5):614-620. doi:10.1093/bioinformatics/btt593.
```
